# Generated by Django 2.2.1 on 2020-01-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=20)),
                ('destinations', models.CharField(max_length=30)),
                ('any_discunts', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('shipping_cost', models.FloatField()),
                ('qty', models.PositiveSmallIntegerField()),
                ('menufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Menufacture')),
            ],
        ),
    ]
